socialweb/blog/urls.py
from django.urls import path, include
from . import views
from .views import *

urlpatterns = [
    path('', views.blog, name='blog'),
    path('Article/<int:pk>', Article.as_view(), name='Article'),
    path('Article/<int:pk>/like/', like_post, name='like-post'),
    path('comment/like/<pk>/', like_comment, name="like-comment"),
    path('reply/like/<pk>/', like_reply, name="like-reply"),
    path('commentsent/<pk>', comment_sent, name='comment-sent'),
    path('comment/delete/<pk>', delet_comment, name='comment-delete'),
    path('reply/<pk>', reply_sent, name='reply-sent'),
    path('reply/delete/<pk>', delet_reply, name='reply_delete'),
    path('addpost/', AddPostView.as_view(), name='addpost'),
    path('Article/edit/<int:pk>', UpdatePostView.as_view(), name='updatepost'),
    path('Article/<int:pk>/remove', DeletePostView.as_view(), name='deletepost'),
]

socialweb/main/urls.py
from django.urls import path, include
from . import views
from .views import Register

urlpatterns = [
    path('', views.main, name='main'),

    path('last/', views.last, name='last'),
    path('test/', views.test, name='test'),
    path('setbar/', views.setbarbar, name='setbar'),



    path('', include('django.contrib.auth.urls')),
    path('register/', Register.as_view(), name='register'),

]

socialweb/socialweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('gallery/', include('gallery.urls')),
    path('blog/', include('blog.urls')),
    path('profiles/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialweb/main/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    class Meta:
        db_table = "MainProfile"

    user = models.OneToOneField('Profile', on_delete=models.CASCADE, related_name='nameuser')
    first_name = models.CharField('Profile', max_length=150, blank=True)
    last_name = models.CharField('Profile', max_length=150, blank=True)
    email = models.EmailField('Profile', blank=True)
    is_staff = models.BooleanField('Profile', default=False)
    is_active = models.BooleanField('Profile', default=True)
    middle_name = models.CharField('Profile', max_length=50, blank=True)
    phone = models.CharField('Profile', max_length=14, blank=True)
    avatar = models.ImageField('Profile', upload_to="prof/%Y/%m/%d", blank=True)
    friends = models.ManyToManyField(User, blank=True, related_name="mainfriends")

    def get_friends(self):
        return self.friends.all()

    def get_friends_no(self):
        return self.friends.all().count()

    def __str__(self):
        return str(self.user)


class Gallery(models.Model):
    class Meta:
        db_table = "MainGallery"

    title = models.CharField('Gallery', max_length=200)
    description = models.TextField('Gallery', blank=True)
    image = models.ImageField('Gallery', default="default1.jpg", upload_to="GIMG/%Y/%m/%d")
    demo_link = models.CharField('Gallery', max_length=200, blank=True)
    source_link = models.CharField('Gallery', max_length=200, blank=True)
    vote_total = models.IntegerField('Gallery', default=0, blank=True)
    vote_ratio = models.IntegerField('Gallery', default=0, blank=True)
    created = models.DateTimeField('Gallery', auto_now_add=True)
    autor = models.ForeignKey('Gallery', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title


class V_Gallery(models.Model):
    class Meta:
        db_table = "MainVGallery"

    title = models.CharField('V_Gallery', max_length=200)
    description = models.TextField('V_Gallery', blank=True)
    video = models.FileField('V_Gallery', default="default.mov", upload_to="GVD/%Y/%m/%d")
    demo_link = models.CharField('V_Gallery', max_length=200, blank=True)
    source_link = models.CharField('V_Gallery', max_length=200, blank=True)
    vote_total = models.IntegerField('V_Gallery', default=0, blank=True)
    vote_ratio = models.IntegerField('V_Gallery', default=0, blank=True)
    created = models.DateTimeField('V_Gallery', auto_now_add=True)
    autor = models.ForeignKey('V_Gallery', on_delete=models.CASCADE, null=True)


class Blog(models.Model):
    class Meta:
        db_table = "MainBlog"

    title = models.CharField('Blog', max_length=255)
    content = models.TextField('Blog', blank=True)
    photo = models.ImageField('Blog', upload_to="blog_photos/%Y/%m/%d/", blank=True)
    time_created = models.DateTimeField('Blog', auto_now_add=True)
    time_update = models.DateTimeField('Blog', auto_now=True)
    autor = models.ForeignKey('Blog', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

socialweb/main/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _




User = get_user_model()


class UserCreationForm(UserCreationForm):
    email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={"autocomplete": "email"}),
    )

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email")

socialweb/main/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import UserCreationForm
from django.contrib.auth import login, authenticate
from itertools import chain
from users.models import Profile
from gallery.models import Gallery, V_Gallery
from blog.models import Blog, CommentBlog, Reply
from django.core.paginator import Paginator
import random
import operator
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from gallery.forms import GaleryForm
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView


@login_required
def main(request):
    ph = Profile.objects.all()
    gl = Gallery.objects.all()
    vd = V_Gallery.objects.all()
    bg = Blog.objects.all()
    cb = CommentBlog.objects.all()
    # ch = list(chain(Gallery.objects.all(), V_Gallery.objects.all(), Blog.objects.all()))
    ch = list(chain(gl, vd, bg))
    ch = sorted(ch, key=operator.attrgetter('created'), reverse=True)
    context = {'profuser': ph, 'gall': gl, 'vgall': vd, 'mblog': bg, 'changemain': ch, 'cbl': cb, }
    return render(request, "main/main.html", context)


@login_required
def test(request):
    ph = Profile.objects.all()
    bg = Blog.objects.all()
    fr = ph.sender.all()
    context = {'profuser': ph, 'mblog': bg, 'fr': fr}
    return render(request, "main/test.html", context)


@login_required
def setbarbar(request):
    ph = Profile.objects.all()
    context = {'profuser': ph}
    return render(request, "main/setbar.html", context)


@login_required
def last(request):
    ph = Profile.objects.all()
    gl = Gallery.objects.all()
    vd = V_Gallery.objects.all()
    bg = Blog.objects.all()
    cb = CommentBlog.objects.all()
    # ch = list(chain(Gallery.objects.all(), V_Gallery.objects.all(), Blog.objects.all()))
    ch = list(chain(gl, vd, bg))
    ch = sorted(ch, key=operator.attrgetter('created'), reverse=True)

    # paginator = Paginator(ch, 3)
    # page = int(request.GET.get('page', 1))
    # ch = paginator.page(page)

    context = {'profuser': ph, 'gall': gl, 'vgall': vd, 'mblog': bg, 'changemain': ch}

    # if request.htmx:
    #     return render(request, "snippets/looplastnwes.html", context)

    return render(request, "main/last_news.html", context)


class Register(View):
    template_name = 'registration/register.html'

    def get(self, request):
        context = {
            'form': UserCreationForm
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('main')
        context = {
            'form': form
        }
        return render(request, self.template_name, context)

socialweb/main/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
            integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
            crossorigin="anonymous"></script>
    <!--    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}"/>-->
    <!--    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>-->
    <!--    <link rel="stylesheet" href="{% static 'css/person_main.css' %}" />-->

    <!--    <link rel="stylesheet" href="{% static 'css/photo.css' %}" />-->
    <!--    <link rel="stylesheet" href="{% static 'css/vid.css' %}" />-->
    <link rel="stylesheet" href="{% static 'css/osn.css' %}"/>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <script src="https://unpkg.com/htmx.org@2.0.3"></script>

    <title>SNJT</title>
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v1.9.4/dist/alpine.js"></script>
</head>

<body>


<div class="container" x-data="{ rightSide: false, leftSide: false }">
    <div class="left-side" :class="{'active' : leftSide}">
        <div class="left-side-button" @click="leftSide = !leftSide">
            <svg
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    stroke-width="2"
                    fill="none"
                    stroke-linecap="round"
                    stroke-linejoin="round"
            >
                <line x1="3" y1="12" x2="21" y2="12"></line>
                <line x1="3" y1="6" x2="21" y2="6"></line>
                <line x1="3" y1="18" x2="21" y2="18"></line>
            </svg>
            <svg
                    stroke="currentColor"
                    stroke-width="2"
                    fill="none"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    viewBox="0 0 24 24"
            >
                <path d="M19 12H5M12 19l-7-7 7-7"/>
            </svg>
        </div>
        <button class="right-side-button" @click="rightSide = !rightSide">
            <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none"
                 stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1">
                <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>
            </svg>
        </button>

        <div class="logo">JTSN</div>
        <div class="side-wrapper">
            <div class="side-title">MENU</div>
            <div class="side-menu">
                <a href="{% url 'main' %}">
                    <svg
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            stroke="currentColor"
                            stroke-width="2"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            viewBox="0 0 24 24"
                    >
                        <path
                                d="M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z"
                        />
                        <path d="M9 22V12h6v10"/>
                    </svg>
                    Home
                </a>
                <a href="{% url 'profile' user.pk %}">
                    <svg
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            stroke="currentColor"
                            stroke-width="2"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            viewBox="0 0 24 24"
                    >
                        <path
                                d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0118 0z"
                        />
                        <circle cx="12" cy="10" r="3"/>
                    </svg>
                    Profile
                </a>
                <a href="{% url 'blog' %}">
                    <svg
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            stroke="currentColor"
                            stroke-width="2"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            viewBox="0 0 24 24"
                    >
                        <path
                                d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"
                        />
                        <path d="M14 2v6h6M16 13H8M16 17H8M10 9H8"/>
                    </svg>
                    Blog
                </a>
                <a href="{% url 'photo' %}">
                    <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            stroke-width="2"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                    >
                        <rect
                                x="3"
                                y="3"
                                width="18"
                                height="18"
                                rx="2"
                                ry="2"
                        />
                        <circle cx="8.5" cy="8.5" r="1.5"/>
                        <path d="M21 15l-5-5L5 21"/>
                    </svg>
                    Galery
                </a>
                <a href="{% url 'video' %}">
                    <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            stroke-width="2"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                    >
                        <rect
                                x="3"
                                y="4"
                                width="18"
                                height="18"
                                rx="2"
                                ry="2"
                        />
                        <path d="M16 2v4M8 2v4M3 10h18"/>
                    </svg>
                    Video
                </a>
            </div>
        </div>

    </div>

    {% block content %}


    {% endblock %}

    <div class="right-side" :class="{ 'active': rightSide }">

        {% include 'main/setbar.html'%}


        <div class="side-wrapper contacts">
            <div class="side-title">CONTACTS</div>
            {% include 'main/test.html'%}
        </div>
    </div>
    <div
            class="overlay"
            @click="rightSide = false; leftSide = false"
            :class="{ 'active': rightSide || leftSide }"
    ></div>
</div>

</body>

</html>

socialweb/main/templates/main/last_news.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<script src="https://unpkg.com/htmx.org@2.0.3"></script>

<div class="main" id="Art">
    <div class="main-container">
        <div class="timeline">
            <!-- из за этого модуля долго думает при переходе между страницами-->
            <div class="timeline-right">

            {% include 'main/snippets/looplastnwes.html' %}

           </div>
        </div>
    </div>
</div>

{% endblock %}

socialweb/main/templates/main/main.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

<div class="main">
    <div class="main-container">
        <div class="timeline">
            <!-- из за этого модуля долго думает при переходе между страницами-->
            <div class="timeline-right">
                {% for el in changemain %}
                {% if el.image %}
                <div class="album box">
                    <div class="status-main">
                        <img src="{%for pr in profuser%}
                                        {% if el.autor_id == pr.user_id %}
                                            {{ pr.avatar.url }}
                                        {% endif %}
                                     {% endfor %}"
                             class="status-img"/>
                        <div class="album-detail">
                            <div class="album-title"><strong><a href="{% url 'profile' el.autor.pk %}">{{ el.autor }}</a></strong> create new
                                <span><a href="{% url 'hole-image' el.pk %}">{{ el.title }}</a></span></div>
                            <div class="album-date">{{ el.created }}</div>
                        </div>
                        <button class="intro-menu"></button>
                    </div>
                    <div class="album-content">
                        <div class="album-photos">
                            <img
                                    src="{{el.image.url}}"
                                    alt=""
                                    class="album-photo"
                            />
                        </div>
                        <hr>
                    <h4>{{el.description}}</h4>
                    </div>
                    <div class="album-actions">
                        {% if user.is_authenticated and user != gall.author %}
                            <a hx-get="{% url 'like-img' el.id %}"
                               hx-target="#like-{{ el.id }}"
                               hx-swap="innerHTML"
                               class="album-action">
                                <svg
                                    stroke="currentColor"
                                    stroke-width="2"
                                    fill="none"
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    class="css-i6dzq1"
                                    viewBox="0 0 24 24"
                            >
                                    {% if user in el.likes.all %}
                                    <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"/>
                                    {% else %}
                                    <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"/>
                                    {% endif %}
                            </svg>
                                <div id="like-{{ el.id }}">{{ el.likes.count }}</div>

                            </a>
                        {% endif %}
                        <a href="{% url 'hole-image' el.pk %}" class="album-action">
                            <svg stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round"
                                 stroke-linejoin="round" class="css-i6dzq1" viewBox="0 0 24 24">
                                <path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z"/>
                            </svg>
                            {% if el.commentsimg.count %}
                                {{ el.commentsimg.count }}
                                {% else %}
                                add comment
                                {% endif %}
                        </a>
                    </div>
                </div>
                {% elif el.video %}
                <div class="album box">
                    <div class="status-main">
                        <img src="{%for pr in profuser%}
                                        {% if el.autor_id == pr.user_id %}
                                            {{ pr.avatar.url }}
                                        {% endif %}
                                     {% endfor %}"
                             class="status-img"/>
                        <div class="album-detail">
                            <div class="album-title"><strong><a href="{% url 'profile' el.autor.pk %}">{{ el.autor }}</a></strong> create new
                                <span><a href="{% url 'hole-video' el.pk %}">{{ el.title }}</a></span></div>
                            <div class="album-date">{{ el.created }}</div>
                        </div>
                        <button class="intro-menu"></button>
                    </div>
                    <div class="album-content">
                        <div class="album-photos">
                            <video
                                    src="{{ el.video.url }}"
                                    class="album-photo"
                                    controls
                            ></video>
                        </div>
                        <hr>
                    <h4>{{el.description}}</h4>
                    </div>
                    <div class="album-actions">
                        {% if user.is_authenticated and user != vgall.author %}
                            <a hx-get="{% url 'like-VG' el.id %}"
                               hx-target="#like-{{ el.id }}"
                               hx-swap="innerHTML"
                               class="album-action">
                                <svg
                                    stroke="currentColor"
                                    stroke-width="2"
                                    fill="none"
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    class="css-i6dzq1"
                                    viewBox="0 0 24 24"
                            >
                                    {% if user in el.likes.all %}
                                    <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"/>
                                    {% else %}
                                    <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"/>
                                    {% endif %}
                            </svg>
                                <div id="like-{{ el.id }}">{{ el.likes.count }}</div>

                            </a>
                        {% endif %}
                        <a href="{% url 'hole-video' el.pk %}" class="album-action">
                            <svg stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round"
                                 stroke-linejoin="round" class="css-i6dzq1" viewBox="0 0 24 24">
                                <path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z"/>
                            </svg>
                            {% if el.commentsvg.count %}
                                {{ el.commentsvg.count }}
                                {% else %}
                                add comment
                                {% endif %}
                        </a>
                    </div>
                </div>
                {% else %}
                <div class="album box">
                    <div class="status-main">
                        <img src="{%for pr in profuser%}
                                        {% if el.autor_id == pr.user_id %}
                                            {{ pr.avatar.url }}
                                        {% endif %}
                                     {% endfor %}"
                             class="status-img"/>
                        <div class="album-detail">
                            <div class="album-title"><strong><a href="{% url 'profile' el.autor.pk %}">{{ el.autor }}</a></strong> create new
                                <span><a href="{% url 'Article' el.pk %}">{{ el.title }}</a></span></div>
                            <div class="album-date">{{ el.created }}</div>
                        </div>
                        <button class="intro-menu"></button>
                    </div>
                    <div class="album-content">
                        <div class="album-photos">
                            {% if el.photo %}
                            <img src="{{el.photo.url}}" alt="" class="album-photo"/>
                                 {% else %}
                            <img src="" alt="" class="album-photo"/>
                                 {% endif %}

                        </div>
                        <hr>
                        {% if el.short_content %}
                        <h4>{{el.short_content}} ...</h4>
                        {% else %}
                        <h4>{{el.content}}</h4>
                        {% endif %}

                    </div>
                    <div class="album-actions">
                        {% if user.is_authenticated and user != blogpost.author %}
                            <a hx-get="{% url 'like-post' el.id %}"
                               hx-target="#like-{{ el.id }}"
                               hx-swap="innerHTML"
                               class="album-action">
                                <svg
                                    stroke="currentColor"
                                    stroke-width="2"
                                    fill="none"
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    class="css-i6dzq1"
                                    viewBox="0 0 24 24"
                            >
                                    {% if user in el.likes.all %}
                                    <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"/>
                                    {% else %}
                                    <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"/>
                                    {% endif %}
                            </svg>
                                <div id="like-{{ el.id }}">{{ el.likes.count }}</div>

                            </a>
                        {% endif %}
                        <a href="{% url 'Article' el.pk %}" class="album-action">
                            <svg stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round"
                                 stroke-linejoin="round" class="css-i6dzq1" viewBox="0 0 24 24">
                                <path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z"/>
                            </svg>
                            {% if el.comments.count %}
                                {{ el.comments.count }}
                                {% else %}
                                add comment
                                {% endif %}
                        </a>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

socialweb/main/templates/main/setbar.html
{% for pr in profuser %}
{% if user.id == pr.user_id %}
<div class="account">
    <button class="account-button">
        <svg
                stroke="currentColor"
                stroke-width="2"
                fill="none"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="css-i6dzq1"
                viewBox="0 0 24 24"
        >
            <path
                    d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"
            />
            <path d="M22 6l-10 7L2 6"/>
        </svg>
    </button>
    <button class="account-button">
        <svg
                stroke="currentColor"
                stroke-width="2"
                fill="none"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="css-i6dzq1"
                viewBox="0 0 24 24"
        >
            <path
                    d="M18 8A6 6 0 006 8c0 7-3 9-3 9h18s-3-2-3-9M13.73 21a2 2 0 01-3.46 0"
            />
        </svg>
    </button>
    <span class="account-user">
        {{ user }}

        <span>
            <ul class="navigation">
                <li>
                    <a class="maina" href="#"> <img src="{{ pr.avatar.url}}" alt="" class="account-profile" alt=""/> <span>▼</span></a>
                    <ul class="subnav">
                        <li><a href="{% url 'profile-edit' pr.pk %}">Settings</a></li>
                        <li><a href="{% url 'my_invites' %}">Invites</a></li>
                        <li><a href="{% url 'profile_list' %}">Friends</a></li>
                        <li>
                            {% if user.is_authenticated %}
                            <a href="{% url 'password_change' %}">
                            Смена пароля
                        </a>
                            {% endif %}
                        </li>
                        <li>{% if user.is_authenticated %}
                            <a href="#">

                            <form id="myForm" method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <a href="javascript:void(0);" id="linkSubmit">LogOut</a>
                            </form>
                            {% else %}
                            <a href="{% url 'login' %}">Авторизация</a>
                            {% endif %}
                            </a>
                        </li>
                    </ul>
            </ul>
        </span>
    </span>
</div>
{% endif %}
{% endfor %}
<!--<span>▼</span>-->
<script>
 document.getElementById('linkSubmit').addEventListener('click', function() {
 document.getElementById('myForm').submit();
 });
</script>