socialweb/blog/urls.py
from django.urls import path, include
from . import views
from .views import *

urlpatterns = [
    path('', views.blog, name='blog'),
    path('Article/<int:pk>', Article.as_view(), name='Article'),
    path('Article/<int:pk>/like/', like_post, name='like-post'),
    path('comment/like/<pk>/', like_comment, name="like-comment"),
    path('reply/like/<pk>/', like_reply, name="like-reply"),
    path('commentsent/<pk>', comment_sent, name='comment-sent'),
    path('comment/delete/<pk>', delet_comment, name='comment-delete'),
    path('reply/<pk>', reply_sent, name='reply-sent'),
    path('reply/delete/<pk>', delet_reply, name='reply_delete'),
    path('addpost/', AddPostView.as_view(), name='addpost'),
    path('Article/edit/<int:pk>', UpdatePostView.as_view(), name='updatepost'),
    path('Article/<int:pk>/remove', DeletePostView.as_view(), name='deletepost'),
]

socialweb/socialweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('gallery/', include('gallery.urls')),
    path('blog/', include('blog.urls')),
    path('profiles/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialweb/users/urls.py
from django.urls import path, include
from . import views
from .views import (
    my_profile,
    profile_edit_view,
    profile_delete_view,
    status_edit_view,
    invites_received_view,
    profiles_list_view,
    invite_profiles_list_view,
    ProfileListView,
    send_invatation,
    remove_from_friends,
    accept_invatation,
    reject_invatation,
)

urlpatterns = [
    path('profile/<int:pk>', my_profile, name='profile'),


    path('profile/edit/<int:pk>', profile_edit_view.as_view(), name='profile-edit'),
    path('status/edit/<int:pk>', status_edit_view.as_view(), name='status-edit'),
    path('profile/edit/', profile_delete_view, name='deleteacc'),
    path('my_invites/', invites_received_view, name='my_invites'),
    path('profile_list/', ProfileListView.as_view(), name='profile_list'),
    path('to_invite_list/', invite_profiles_list_view, name='to_invite_list'),
    path('to_invite_list/', invite_profiles_list_view, name='to_invite_list'),
    path('send_invate/<int:pk>', send_invatation, name='send-invate'),
    path('remove_friend/<int:pk>', remove_from_friends, name='remove-friend'),
    path('accept_invites/accept/<int:pk>', accept_invatation, name='accept-invite'),
    path('accept_invites/reject/<int:pk>', reject_invatation, name='reject-invite'),
]

socialweb/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import uuid
from users.models import Profile


class Blog(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название')
    content = models.TextField(blank=True, verbose_name='Контент')
    photo = models.ImageField(upload_to="blog_photos/%Y/%m/%d/", blank=True, verbose_name='Фото')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    autor = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    likes = models.ManyToManyField(User, related_name="likedposts", through="LikedPost")
    short_content = models.CharField(max_length=100, default='', blank=True)

    class Meta:
        ordering = ['-created']

    def save(self, *args, **kwargs):
        if not self.short_content:
            self.short_content = self.content[:100]
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class CommentBlog(models.Model):
    comment = models.CharField(max_length=150)
    time_created = models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='comments')
    likes = models.ManyToManyField(User, related_name="likedcomments", through="LikedComment")
    name = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, related_name='name')
    post = models.ForeignKey(Blog, related_name='comments', on_delete=models.CASCADE)
    id = models.CharField(max_length=100, default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        try:
            return f'{self.autor.username} : {self.comment[:30]}'
        except:
            return f'no author : {self.comment[:30]}'

    class Meta:
        ordering = ['-time_created']


class Reply(models.Model):
    comment = models.CharField(max_length=150)
    time_created = models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='replies')
    name = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, related_name='namerep')
    likes = models.ManyToManyField(User, related_name='likedreplies', through='LikedReply')
    parent_comment = models.ForeignKey(CommentBlog, related_name='replies', on_delete=models.CASCADE)
    id = models.CharField(max_length=100, default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        try:
            return f'{self.autor.username} : {self.comment[:30]}'
        except:
            return f'no author : {self.comment[:30]}'

    class Meta:
        ordering = ['time_created']


class LikedPost(models.Model):
    post = models.ForeignKey(Blog, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} : {self.post.title}'


class LikedComment(models.Model):
    comment = models.ForeignKey(CommentBlog, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} : {self.comment.comment[:30]}'


class LikedReply(models.Model):
    reply = models.ForeignKey(Reply, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} : {self.reply.comment[:30]}'

socialweb/main/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    class Meta:
        db_table = "MainProfile"

    user = models.OneToOneField('Profile', on_delete=models.CASCADE, related_name='nameuser')
    first_name = models.CharField('Profile', max_length=150, blank=True)
    last_name = models.CharField('Profile', max_length=150, blank=True)
    email = models.EmailField('Profile', blank=True)
    is_staff = models.BooleanField('Profile', default=False)
    is_active = models.BooleanField('Profile', default=True)
    middle_name = models.CharField('Profile', max_length=50, blank=True)
    phone = models.CharField('Profile', max_length=14, blank=True)
    avatar = models.ImageField('Profile', upload_to="prof/%Y/%m/%d", blank=True)
    friends = models.ManyToManyField(User, blank=True, related_name="mainfriends")

    def get_friends(self):
        return self.friends.all()

    def get_friends_no(self):
        return self.friends.all().count()

    def __str__(self):
        return str(self.user)


class Gallery(models.Model):
    class Meta:
        db_table = "MainGallery"

    title = models.CharField('Gallery', max_length=200)
    description = models.TextField('Gallery', blank=True)
    image = models.ImageField('Gallery', default="default1.jpg", upload_to="GIMG/%Y/%m/%d")
    demo_link = models.CharField('Gallery', max_length=200, blank=True)
    source_link = models.CharField('Gallery', max_length=200, blank=True)
    vote_total = models.IntegerField('Gallery', default=0, blank=True)
    vote_ratio = models.IntegerField('Gallery', default=0, blank=True)
    created = models.DateTimeField('Gallery', auto_now_add=True)
    autor = models.ForeignKey('Gallery', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title


class V_Gallery(models.Model):
    class Meta:
        db_table = "MainVGallery"

    title = models.CharField('V_Gallery', max_length=200)
    description = models.TextField('V_Gallery', blank=True)
    video = models.FileField('V_Gallery', default="default.mov", upload_to="GVD/%Y/%m/%d")
    demo_link = models.CharField('V_Gallery', max_length=200, blank=True)
    source_link = models.CharField('V_Gallery', max_length=200, blank=True)
    vote_total = models.IntegerField('V_Gallery', default=0, blank=True)
    vote_ratio = models.IntegerField('V_Gallery', default=0, blank=True)
    created = models.DateTimeField('V_Gallery', auto_now_add=True)
    autor = models.ForeignKey('V_Gallery', on_delete=models.CASCADE, null=True)


class Blog(models.Model):
    class Meta:
        db_table = "MainBlog"

    title = models.CharField('Blog', max_length=255)
    content = models.TextField('Blog', blank=True)
    photo = models.ImageField('Blog', upload_to="blog_photos/%Y/%m/%d/", blank=True)
    time_created = models.DateTimeField('Blog', auto_now_add=True)
    time_update = models.DateTimeField('Blog', auto_now=True)
    autor = models.ForeignKey('Blog', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

socialweb/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q


# class User(models.Model):
#     """User model"""
#     username = models.CharField(max_length=150, unique=True)
#     first_name = models.CharField(max_length=150, blank=True)
#     last_name = models.CharField(max_length=150, blank=True)
#     email = models.EmailField(blank=True)
#     is_staff = models.BooleanField(default=False)
#     is_active = models.BooleanField(default=True)
#     middle_name = models.CharField(max_length=50, blank=True)
#     first_login = models.DateTimeField(null=True)
#     phone = models.CharField(max_length=14, blank=True)
#     avatar = models.ImageField(upload_to="prof/%Y/%m/%d", blank=True, null=True)
#     friends = models.ManyToManyField('User', blank=True)
#     def __str__(self):
#         return self.username
class ProfileManager(models.Manager):

    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))
        print(qs)

        accepted = set([])
        for rel in qs:
            if rel.status == 'accepted':
                accepted.add(rel.receiver)
                accepted.add(rel.sender)
        print(accepted)

        available = [profile for profile in profiles if profile not in accepted]
        print(available)
        return available

    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='nameuser')
    first_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    email = models.EmailField(blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    middle_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=14, blank=True)
    avatar = models.ImageField(upload_to="prof/%Y/%m/%d", blank=True, default="default.jpeg")
    friends = models.ManyToManyField(User, blank=True, related_name='friends')
    update = models.DateTimeField(auto_now=True)
    create = models.DateTimeField(auto_now_add=True)
    birth_date = models.DateField(blank=True, null=True)
    location = models.CharField(max_length=100, blank=True, null=True)
    proffecy = models.CharField(max_length=100, blank=True, null=True)
    bg_PIC = models.ImageField(upload_to="prof/%Y/%m/%d", blank=True, default="defbg.jpg")
    status = models.CharField(max_length=250, blank=True, null=True)

    objects = ProfileManager()

    def get_friends(self):
        return self.friends.all()

    def get_friends_no(self):
        return self.friends.all().count()

    def __str__(self):
        return str(self.user)


STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)


class RelationshipManager(models.Manager):
    def invatations_received(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status='send')
        return qs


class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    update = models.DateTimeField(auto_now=True)
    create = models.DateTimeField(auto_now_add=True)

    objects = RelationshipManager()

    def __str__(self):
        return f'{self.sender}-{self.receiver}-{self.status}'

socialweb/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _
from .models import *


class ProfileEdit(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'avatar',
                  'proffecy', 'bg_PIC', 'location']


class StatusEdit(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['status']

socialweb/users/templates/users/deleteacc.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}


<h1>Delete Account</h1>
<p>Are you sure you want to delete your account?</p>

<form method='POST'>
    {% csrf_token %}
    <button type="submit" class="btn-red mt-6">Yes, I want to delete my account</button>
    <a class="button secondaryAction ml-1" href="">Cancel</a>
</form>

{% endblock %}

socialweb/users/templates/users/my_invites.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

<div class="main">
    <div class="main-container">
        <div class="timeline">
            <div class="timeline-right">
                <div class="album box">
                    <h1>My Invites</h1>
                    {% if is_empty %}
                    <h1>No invitation here...</h1>
                    {% endif %}

                    {% for obj in qs %}
                    <div class="album-photos">
                        <img style="width: 100px; height: 100px;" src="{{obj.avatar.url}}" alt="">
                        <div class="album-right">
                            {{obj.first_name}} {{obj.last_name}} @{{obj.user}}<br>
                            <hr>
                            <div class="album-photo">
                                <button type="button" value="Перейти" class="btn btn-outline-info"
                                        onclick="window.location='{% url 'profile' obj.pk %}'">See Profile
                                </button>
                            </div>
                            <div class="album-photo">
                                <form action="{% url 'accept-invite' obj.pk %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="'profile_pk" value="{{obj.pk}}">
                                    <button type="submit" class="btn btn-outline-success">Accept
                                    </button>
                                </form>
                            </div>
                            <div class="album-photo">
                                <form action="{% url 'reject-invite' obj.pk %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="'profile_pk" value="{{obj.pk}}">
                                    <button type="submit" class="btn btn-outline-danger">Reject</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <hr>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

socialweb/users/templates/users/profile-edit.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

<div class="main">
    <div class="main-container">
        <div class="timeline">
            <div class="timeline-right">
                <div class="album box">
                    <h1 class="mb-2">Edit Profile</h1>
                    <div class="text-center flex flex-col items-center">
                        <img id="avatar" class="w-36 h-36 rounded-full object-cover mb-4"
                             src="{{ profile.avatar.url }}"
                        alt="Фото профиля"
                        style="width: 400px; height: 400px;"/>
                        <div class="text-center max-w-md">
                            <h1 id="realname">
                                {{ profile.first_name }} {{ profile.last_name }}
                            </h1>
                            <div class="text-gray-400 mb-2 -mt-3">@{{ user }}</div>
                        </div>
                    </div>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Submit</button>
                        <a class="button secondaryAction ml-1" href="{% url 'profile' user.pk %}">Cancel</a>
                    </form>
                    <a class="mt-12 hover:underline text-gray-500" href="{% url 'deleteacc'%}">Delete Profile</a>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    // This updates the avatar
    const fileInput = document.querySelector('input[type="file"]');

    fileInput.addEventListener('change', (event) => {
    const file = event.target.files[0];
    const image = document.querySelector('#avatar');

    if (file && file.type.includes('image')) {
        const url = URL.createObjectURL(file);
        image.src = url;
    }
    });

    // This updates the name
    const realnameInput = document.getElementById('id_realname');
    const realnameOutput = document.getElementById('realname');

    realnameInput.addEventListener('input', (event) => {
    realnameOutput.innerText = event.target.value;
    });



</script>

{% endblock %}

socialweb/users/templates/users/profile.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/puw.js' %}"></script>

<div class="container" x-data="{ rightSide: false, leftSide: false }">
    <div class="main">
        <div class="main-container">
            <div class="profile">
                <!--avatar-->
                <div class="profile-avatar">
                    <img
                            src="{{ profile.avatar.url }}"
                            alt=""
                            class="profile-img"
                    />
                    <div class="profile-name">{{ profile.first_name }}</div>
                </div>
                <!--background-->
                <img
                        src="{{ profile.bg_PIC.url }}"
                        alt=""
                        class="profile-cover"
                />
            </div>
            <div class="timeline">
                <div class="timeline-left">
                    <!--user info-->
                    <div class="intro box">
                        <div class="intro-title">
                            Introduction
                        </div>
                        <div class="info">
                            <div class="info-item">
                                Last login at <a href="#">{{ profile.user.last_login }}</a>
                            </div>
                            <div class="info-item">
                                Profession <a href="#">{{ profile.proffecy }}</a>
                            </div>
                            <div class="info-item">
                                Live in <a href="#">{{ profile.location }}</a>
                            </div>
                            <div class="info-item">
                                Real name <a href="#">{{ profile.first_name }} {{ profile.last_name }}</a>
                            </div>
                        </div>
                    </div>
                    <!--friends box-->
                    <div class="pages box">

                        <div class="intro-title">
                            Your friends
                            Count: {{ profile.get_friends_no }}
                        </div>
                        {% for friends in profile.friends.all %}

                        <div class="user">

                            <img
                                    src="{%for pr in profuser %}{% if pr.user_id == friends.id %}{{ pr.avatar.url }}{% endif %}{% endfor %}"
                                    alt=""
                                    class="user-img"
                            />
                            {%for pr in profuser %}{% if pr.user_id == friends.id %}
                            <div class="username">{{ pr.first_name }} {{ pr.last_name }}</div>
                            {% endif %}{% endfor %}
                        </div>


                        {% endfor %}
                    </div>
                </div>
                <div class="timeline-right">
                    <!--xz-->
                    <div class="status box">
                        <form action="{% url 'status-edit' user.pk%}" method="POST" enctype="multipart/form-data">
                            <div class="status-menu">
                                <a class="status-menu-item active" href="#"
                                >Status</a
                                >
                            </div>
                            <div class="status-main">
                                <img
                                        src="{{ profile.avatar.url }}"
                                        class="status-img"
                                />
                                {% csrf_token %}
                                {{ form.as_p }}
                                <textarea
                                        type="text"
                                        name="status"
                                        maxlength="250"
                                        id="id_status"
                                        class="status-textarea"
                                        placeholder="{{ profile.status }}"
                                ></textarea>
                            </div>
                            {% if user.is_authenticated and user.id == profile.user_id %}
                            <div class="status-actions">
                                <button class="status-share" type="submit">Share</button>
                            </div>
                            {% endif %}
                        </form>
                    </div>
                    <!--add all-->
                    {% if user.is_authenticated and user.id == profile.user_id %}
                    <div class="album box">
                        <div class="status-menu">
                            <a data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0"
                               class="active status-menu-item" aria-current="true" aria-label="Slide 1" href="#"
                            >Add Image</a
                            >
                            <a type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
                               aria-label="Slide 2" href="#" class="status-menu-item">Add Video</a>
                            <a type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
                               aria-label="Slide 3" href="#" class="status-menu-item">Add Post</a>
                        </div>
                        <hr>
                        <div class="status-main">
                            <div id="carouselExampleIndicators" class="carousel slide">

                                <div class="carousel-inner">
                                    <div class="carousel-item active">
                                        <div class="status-menu">
                                            <h1>Add image</h1>
                                            <hr>
                                            <form action="{% url 'addimage' %}" method="post"
                                                  enctype="multipart/form-data">
                                                {% csrf_token %}
                                                <div class="form-error">{{ form.non_field_errors }}</div>
                                                <input type="text" name="title" maxlength="200" required=""
                                                       aria-invalid="true" id="id_title">: title
                                                <textarea name="description" cols="40" rows="10"
                                                          id="id_description"></textarea>: description
                                                <p>
                                                    <label for="id_image">Image:</label>
                                                    <input type="file" name="image" accept="image/*" id="id_image">
                                                </p>

                                                <button>Добавить</button>
                                            </form>
                                        </div>
                                    </div>
                                    <div class="carousel-item">
                                        <div class="status-menu">
                                            <h1>Add videos</h1>
                                            <hr>
                                            <form action="{% url 'addvideo' %}" method="post"
                                                  enctype="multipart/form-data">
                                                {% csrf_token %}
                                                <div class="form-error">{{ form.non_field_errors }}</div>
                                                <input type="text" name="title" maxlength="200" required=""
                                                       id="id_title">: title
                                                <textarea name="description" cols="40" rows="10"
                                                          id="id_description"></textarea>: description
                                                <p>
                                                    <label for="id_video">Video:</label>
                                                    <input type="file" name="video" id="id_video">
                                                </p>
                                                <button>Добавить</button>
                                            </form>
                                        </div>
                                    </div>
                                    <div class="carousel-item">
                                        <div class="status-menu">
                                            <h1>Add post</h1>
                                            <hr>
                                            <form action="{% url 'addpost' %}" method="post"
                                                  enctype="multipart/form-data">
                                                {% csrf_token %}
                                                <div class="form-error">{{ form.non_field_errors }}</div>
                                                <input type="text" name="title" maxlength="255" required=""
                                                       id="id_title">: title
                                                <textarea name="content" cols="40" rows="10" id="id_content"></textarea>:
                                                description
                                                <p>
                                                    <label for="id_photo">Фото:</label>
                                                    <input type="file" name="photo" accept="image/*" id="id_photo">
                                                </p>
                                                <button>Добавить</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

socialweb/users/templates/users/status-edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Submit</button>
                        <a class="button secondaryAction ml-1" href="{% url 'profile' user.pk %}">Cancel</a>
                    </form>
</body>
</html>

socialweb/users/templates/users/to_invite_list.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

<div class="main">
    <div class="main-container">
        <div class="timeline">
            <div class="timeline-right">
                <div class="album box">
                    <h1>Invite friends</h1>
                    <ul>
                        {% for item in qs %}
                        <li>
                            {{ item }}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}